src/annotation/urls.py
"""Defines the routing table of the application."""
from . import views
from django.urls import path

app_name = "annotation"
urlpatterns = [
    path("new", views.NewAnnotationView.as_view(), name="new-annotation"),
    path("<int:id>", views.AnnotateView.as_view(), name="annotate"),
    path("api/entries/<int:entry_id>",
         views.GetEntryContentsView.as_view(),
         name="get-entry"),
    path("complete",
         views.MarkAnnotationCompleteView.as_view(),
         name="mark-complete"),
    path("save", views.SaveAnnotationView.as_view(), name="save"),
    path("thank-you", views.ThankYouView.as_view(), name="thank-you"),
    path("", views.IndexView.as_view(), name="index"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include("annotation.urls")),
]

src/annotation/views/annotate.py
"""The view for annotating an entry."""
from annotation.models.annotation import Annotation
from annotation.models.entry import Entry
from annotation.models.entrypage import EntryPage
from annotation.views.utils import get_image_path
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views import View


class AnnotateView(LoginRequiredMixin, View):
    """Implements the annotation view."""

    template_name = "annotation/annotate.html"
    thank_you_page = 'annotation:thank-you'
    index_page = 'annotation:index'

    def get(self, request, id: int):
        """Handle the GET request.

        Parameters
        ----------
        request: HttpRequest, required
            The request object.
        id: int, required
            The id of the annotation.
        """
        user_id = request.user.id
        current_annotation = self.__get_in_progress_annotation(user_id, id)
        if current_annotation is not None:
            return render(request,
                          self.template_name,
                          context=self.__build_template_context(
                              current_annotation.entry))
        else:
            return redirect(self.index_page)

    def __build_template_context(self, entry: Entry) -> dict:
        entry_pages = EntryPage.objects.filter(entry=entry)
        pages = sorted([e.page for e in entry_pages], key=lambda p: p.page_no)
        page_images = [get_image_path(p) for p in pages]
        return {'entry_id': entry.id, 'page_images': page_images}

    def __get_in_progress_annotation(self, user_id: int,
                                     annotation_id: int) -> Annotation | None:
        return Annotation.objects.filter(user_id=user_id,
                                         id=annotation_id).first()

src/annotation/views/getentrycontents.py
"""The view for retrieving entry contents."""
from ..models.annotation import Annotation
from ..models.entry import Entry
from ..models.entrypage import EntryPage
from ..models.page import Page
from .utils import get_image_path
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.http import JsonResponse
from django.views import View


class GetEntryContentsView(LoginRequiredMixin, View):
    """Implements the view for retrieving the contents of the specified entry."""

    def get(self, request, entry_id: int) -> JsonResponse | Http404:
        """Retrieve the contents for the specified entry.

        Parameters
        ----------
        request: HttpRequest, required
            The HttpRequest object.
        entry_id: int, required
            The id of the entry for which to load the data.

        Returns
        -------
        response: JsonResponse or Http404
            The response data.
            If the response is a JsonResponse, then it contains the following fields:
            - 'contents': the text of the entry
        """
        try:
            entry = Entry.objects.get(pk=entry_id)
            annotation = Annotation.objects.filter(entry=entry,
                                                   user=request.user).first()

            entry_page = EntryPage.objects.filter(entry=entry)\
                                          .first()

            data = {
                'contents': annotation.text,
                'current_page': get_image_path(entry_page.page),
                'previous_page': None,
                'next_page': None
            }
            return JsonResponse(data)
        except (Page.DoesNotExist, Annotation.DoesNotExist):
            raise Http404()

src/annotation/views/index.py
"""The index view."""
from annotation.models.annotation import Annotation
from annotation.models.evaluationinterval import EvaluationInterval
from dataclasses import dataclass
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.utils import timezone
from django.views import View


class IndexView(LoginRequiredMixin, View):
    """Implements the index view."""

    template_name = "annotation/index.html"

    def get(self, request):
        """Handle the GET request.

        Parameters
        ----------
        request: HttpRequest, required
            The request object.
        """
        annotations = Annotation.objects\
            .filter(user=request.user)\
            .order_by('-row_update_timestamp')
        statistics = UserStatisticsCalculator.calculate_statistics(annotations)
        annotations = [(a.id, a.title_word,
                        Annotation.AnnotationStatus(a.status).label,
                        a.status != Annotation.AnnotationStatus.COMPLETE)
                       for a in annotations]

        return render(request,
                      self.template_name,
                      context={
                          'annotations': annotations,
                          'statistics': statistics
                      })


@dataclass
class StatisticItem:
    """Defines a container for statistics."""

    num_annotations: int
    num_symbols: int


@dataclass
class UserStatistics:
    """Contains user statistics."""

    grand_total: StatisticItem
    per_status: list[tuple[Annotation.AnnotationStatus, StatisticItem]]
    current_interval: list[tuple[str, StatisticItem]]


class UserStatisticsCalculator:
    """Implements the logic for calculating user statistics."""

    @staticmethod
    def calculate_statistics(annotations: list[Annotation]) -> UserStatistics:
        """Calculate the statistics from the provided annotations.

        Parameters
        ----------
        annotations: list of Annotation, required
            The annotations for which to calculate statistics.

        Returns
        -------
        stats: UserStatistics
            The statistics.
        """
        grand_total = UserStatisticsCalculator.calculate_grand_total_stats(
            annotations)
        per_status = UserStatisticsCalculator.calculate_stats_per_status(
            annotations)
        current_interval = UserStatisticsCalculator.calculate_stats_for_current_interval(
            annotations)
        return UserStatistics(
            grand_total, per_status,
            [current_interval] if current_interval is not None else [])

    @staticmethod
    def calculate_grand_total_stats(
            annotations: list[Annotation]) -> StatisticItem:
        """Calculate the grand total statistics.

        Parameters
        ----------
        annotations: list of Annotation, required
            The annotations of the user.

        Returns
        -------
        stats: StatisticItem
            The statistics.
        """
        grand_total_annotations = [
            a for a in annotations
            if a.status != Annotation.AnnotationStatus.IN_PROGRESS
        ]
        grand_total = UserStatisticsCalculator.calculate_stats(
            grand_total_annotations)
        return grand_total

    @staticmethod
    def get_current_interval() -> EvaluationInterval | None:
        """Get the current interval.

        Returns
        -------
        interval: EvaluationInterval
            The current interval or None.
        """
        now = timezone.now()
        return EvaluationInterval.objects\
                                 .filter(start_date__lte=now, end_date__gt=now)\
                                 .first()

    @staticmethod
    def calculate_stats_for_current_interval(
            annotations: list[Annotation]) -> tuple[int, StatisticItem] | None:
        """Calculate the statistics per year.

        Parameters
        ----------
        annotations: list of Annotation, required
            The annotations of the user.

        Returns
        -------
        stats: list of (int, StatisticItem) tuples
            The statistics per year as a list of (year, StatisticItem) tuples.
        """
        interval = UserStatisticsCalculator.get_current_interval()
        if interval is None:
            return None
        annotations = [
            a for a in annotations
            if a.status != Annotation.AnnotationStatus.IN_PROGRESS
        ]

        def is_in_interval(interval, annotation):
            dt = annotation.row_creation_timestamp
            return interval.contains(dt.date())

        annotations = [a for a in annotations if is_in_interval(interval, a)]
        return (interval.name,
                UserStatisticsCalculator.calculate_stats(annotations))

    @staticmethod
    def calculate_stats_per_status(
        annotations: list[Annotation]
    ) -> list[tuple[Annotation.AnnotationStatus, StatisticItem]]:
        """Calculate the statistics per status.

        Parameters
        ----------
        annotations: list of Annotation, required
            The annotations of the user.

        Returns
        -------
        stats: list of (Annotation.AnnotationStatus, StatisticItem) tuples
            The statistics per year as a list of (status, StatisticItem) tuples.
        """
        statuses = [
            Annotation.AnnotationStatus.IN_PROGRESS,
            Annotation.AnnotationStatus.CONFLICT,
            Annotation.AnnotationStatus.COMPLETE
        ]
        stats = []

        for status in statuses:
            data = [a for a in annotations if a.status == status]
            item = UserStatisticsCalculator.calculate_stats(data)
            stats.append((status, item))
        return stats

    @staticmethod
    def calculate_stats(annotations: list[Annotation]) -> StatisticItem:
        """Calculate the statistics for the provided list of annotations.

        Parameters:
        ----------
        annotations: list of Annotation, required
            The annotations from which to calculate the statistics.

        Returns
        -------
        stats: StatisticItem
            The statistics calculated from the annotations.
        """
        num_symbols = sum(len(a.text) for a in annotations)
        return StatisticItem(num_annotations=len(annotations),
                             num_symbols=num_symbols)

src/annotation/views/markcomplete.py
"""The view for marking an annotation as complete."""
from typing import Tuple
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import View
from annotation.models.annotation import Annotation
from annotation.models.entry import Entry
from annotation.utils.xml2edtlrmd import Marks
from annotation.views.viewsettings import MAX_CONCURRENT_ANNOTATORS


class MarkAnnotationCompleteView(LoginRequiredMixin, View):
    """Implements the view for marking an annotation as being complete."""

    index_page = "annotation:index"
    annotate_page = "annotation:annotate"

    def post(self, request):
        """Save the annotation from the request body and mark it as complete."""
        entry_id, contents = self.__parse_request_body(request)
        is_valid, error = self.__validate(contents, entry_id)
        if not is_valid:
            annotation = Annotation.objects.get(entry=entry_id,
                                                user=request.user)
            self.__update_annotation(annotation, contents)
            messages.error(request, error, extra_tags="danger")
            return redirect(self.annotate_page, id=annotation.id)
        self.__mark_annotation_complete(entry_id, contents, request.user)
        self.__check_conflicts(entry_id)
        return redirect(self.index_page)

    def __validate(self, text: str, entry_id: int) -> Tuple[bool, str | None]:
        entry = Entry.objects.get(id=entry_id)
        formatted_headword = f'{Marks.BOLD}{entry.title_word_normalized}{Marks.BOLD}'
        content_length = len(text) if text is not None else 0
        if content_length <= len(formatted_headword):
            return (False, _("Entry text is too short."))
        return (True, None)

    def __check_conflicts(self, entry_id: int):
        entry_annotations = Annotation.objects.filter(entry=entry_id)\
            .exclude(status=Annotation.AnnotationStatus.IN_PROGRESS)
        if len(entry_annotations) < MAX_CONCURRENT_ANNOTATORS:
            return

        status = Annotation.AnnotationStatus.COMPLETE
        if self.__have_conflicts(entry_annotations):
            status = Annotation.AnnotationStatus.CONFLICT

        for annotation in entry_annotations:
            annotation.version = annotation.version + 1
            annotation.status = status
            annotation.save()

    def __have_conflicts(self, entry_annotations) -> bool:
        iterator = iter(entry_annotations)

        first = next(iterator).text
        for item in iterator:
            if first != item.text:
                return True

        return False

    def __mark_annotation_complete(self, entry_id: int, text: str, user: User):
        annotation = Annotation.objects.get(entry=entry_id, user=user)
        self.__update_annotation(annotation, text,
                                 Annotation.AnnotationStatus.COMPLETE)

    def __update_annotation(self,
                            annotation: Annotation,
                            text: str,
                            status: Annotation.AnnotationStatus = None):

        annotation.set_text(text)
        if status is not None:
            annotation.status = status
        annotation.row_update_timestamp = timezone.now()
        annotation.version += 1
        annotation.save()

    def __parse_request_body(self, request) -> Tuple[int, object]:
        text = request.POST['text']
        entry_id = int(request.POST['entry-id'])
        return entry_id, text

src/annotation/views/saveannotation.py
"""The view for saving an annotation."""
from typing import Tuple

from annotation.models.annotation import Annotation
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.shortcuts import redirect
from django.utils import timezone
from django.views import View


class SaveAnnotationView(LoginRequiredMixin, View):
    """Implements the view for saving an annotation."""

    annotate_page = 'annotation:annotate'
    index_page = "annotation:index"

    def post(self, request):
        """Save the annotation from the request body.

        Parameters
        ----------
        request: HttpRequest, required
            The HTTP request object.
        """
        entry_id, text = self.__parse_request_body(request)
        annotation = Annotation.objects.get(entry=entry_id, user=request.user)
        # The `get()` method throws a `DoesNoExist` exception if the annotation is not found
        self.__update_annotation(annotation, text)
        return redirect(self.annotate_page, id=annotation.id)

    def __update_annotation(self, annotation: Annotation, text: str):
        annotation.set_text(text)
        annotation.row_update_timestamp = timezone.now()
        annotation.status = Annotation.AnnotationStatus.IN_PROGRESS
        annotation.save()

    def __parse_request_body(self, request) -> Tuple[int, HttpRequest]:
        text = request.POST['text']
        entry_id = int(request.POST['entry-id'])
        return entry_id, text

src/annotation/views/thankyou.py
"""The view that is displayed when there are no more entries to annotate."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View


class ThankYouView(LoginRequiredMixin, View):
    """Implements the view that displays a thank you message when there are no entries to annotate."""

    template_name = "annotation/thank-you.html"

    def get(self, request):
        """Handle the GET request.

        Parameters
        ----------
        request: HttpRequest, required
            The request object.
        """
        return render(request, self.template_name)

src/annotation/views/utils.py
"""Defines utility methods for views."""
from annotation.models.page import Page
from annotation.apps import AnnotationConfig


def get_image_path(page: Page | None) -> str:
    """Get the image path of the specified page.

    Parameters
    ----------
    page: Page, required
        The page for which to get the image path.

    Returns
    -------
    image_path: str or None
        The image path of the image, or None if the page is None.
    """
    if page is None:
        return None
    return f'/{AnnotationConfig.name}/{page.image_path}'

src/annotation/templates/annotation/annotate.html
{% extends "./annotation-base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Annotate text"  %}{% endblock %}

{% block links %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block content %}
<main>
{% if messages %}
   {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
   {% endfor %}
{% endif %}

<div id="editor-container" class="row">
  <div class="col-md-6">
    {% include "./controls/page-carousel.html"  %}
  </div>
  <div class="col-md-6">
    <div id="editor-container" class="sticky-top">
      <textarea id="editor">
      </textarea>
      <!-- buttons -->
      <div id="buttons-row" class="row align-items-end justify-content-start">
	<div class="col-md-8 offset-md-4">
	  <div class="d-flex flex-row-reverse bd-highlight">
	    <form method="post" action="{% url 'annotation:save' %}">
	      {% csrf_token %}
	      <input type="hidden" name="text" value="">
	      <input type="hidden" name="entry-id" value="{{entry_id}}">
	      <button type="submit" id="btn-save-annotation"
		      class="btn btn-primary" value="" >
		<i class="bi bi-save"></i>
		{% translate 'Save annotation' %}
	      </button>
	    </form>
	    <form method="post" action="{% url 'annotation:mark-complete' %}">
	      {% csrf_token %}
	      <input type="hidden" name="text" value="">
	      <input type="hidden" name="entry-id" value="{{entry_id}}">
	      <button type="submit" id="btn-mark-complete"
		      class="btn btn-success">
		<i class="bi bi-check2"></i>
		{% translate "Mark complete" %}
	      </button>
	    </form>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>

</main>
{% endblock %}

{% block page_scripts %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script src="{% static 'annotation/js/dom-utils.js' %}"></script>
<script src="{% static 'annotation/js/page-carousel.js' %}"></script>
<script src="{% static 'annotation/js/annotation-editor.js' %}"></script>
<script src="{% static 'annotation/js/annotation-flow.js' %}"></script>
<script>

  let annotationFlow = new AnnotationFlow('image-container', 'editor',
					  'btn-save-annotation', 'btn-mark-complete',
					  ['text']);
  // TODO: Pass full url using {% url } instead of hardcoding in class
  annotationFlow.initialize({{entry_id}});

</script>
{% endblock %}

src/annotation/templates/annotation/annotation-base.html
{% extends "./base.html" %}
{% load i18n %}
{% load static %}

{% block header %}
  {% include "./controls/navbar.html" %}
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
  </script>
{% block page_scripts %}
{% endblock %}
{% endblock %}

src/annotation/templates/annotation/base.html
<!doctype html>
<html lang="en-US">
  {% load i18n %}
  {% load static %}

<head>
	<meta charset="utf-8" />
	<title>
	  {% block title %}{% endblock %} - {% translate "eDTLR annotator" %}
	</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
	      rel="stylesheet"
	      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
	      crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link rel="shortcut icon" type="image/png" href="{% static 'annotation/assets/png/edtlr.png' %}"/>
	{% block links %}

	{% endblock %}

	<link rel="stylesheet" href="{% static 'annotation/assets/style.css' %}">

</head>

  <body>
    {% block header %}
    {% endblock %}
    <div id="content" class="container-fluid">
      {% block content %}{% endblock %}
    </div>
    <footer class="py-3 my-4">
      <p class="text-center text-muted">
        <span>&copy; {% now 'Y' %}</span>
      </p>
    </footer>
    {% block scripts %}
    {% endblock %}
</body>

</html>

src/annotation/templates/annotation/index.html
{% extends "./annotation-base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Annotate text" %}{% endblock %}


{% block content %}
<main class="container centered-content">
  <div class="content-wrapper">
    <div class="user-annotations-header">
      <h2>{% translate "My annotations" %}</h2>
      <a class="btn btn-success" role="button" href="{% url 'annotation:new-annotation' %}">
        <i class="bi bi-file-earmark-plus"></i>
        {% translate "New annotation" %}
      </a>
    </div>
    <div class="user-annotations">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>{% translate "title word"|capfirst %}</th>
            <th>{% translate "status"|capfirst %}</th>
          </tr>
        </thead>
        <tbody>
          {% for id, title_word, status, is_editable in annotations %}
          <tr>
            <td>
              {% if is_editable %}
              <a href="{% url 'annotation:annotate' id=id %}">
                {{ title_word }}
              </a>
              {% else %}
              {{ title_word }}
              {% endif %}
            </td>
            <td> {{ status }} </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% include "./controls/user-statistics.html" %}
</main>
{% endblock %}

src/annotation/templates/annotation/thank-you.html
{% extends "./annotation-base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Thank you!"  %}{% endblock %}

{% block content %}
<main>
  <div class="row">
    <div class="card">
      <div class="card-body">
	<h5 class="card-title"> {% translate 'No pages to annotate' %}</h5>
	<p class="card-text"> {% translate 'There are no pages to annotate. Thank you!' %}</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

src/annotation/templates/annotation/validate.html
{% extends "./annotation-base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Validate text"  %}{% endblock %}

{% block links %}
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
<div id="editor-container" class="row">
  <div class="col-md-6">
    <div id="image-container">
      <img id="image" class="figure-img img-fluid rounded"
	   src=""/>
    </div>
  </div>
  <div class="col-md-6">
    <div id="editor">
    </div>
  </div>
</div>
<!-- buttons -->
<div id="buttons-row" class="row align-items-end justify-content-start">
  <div class="col-md-4 offset-md-8">
    <div class="d-flex flex-row-reverse bd-highlight">
      <form method="post" action="{% url 'annotation:save' %}">
	{% csrf_token %}
	<input type="hidden" name="contents" value="">
	<button type="submit" id="btn-save-annotation"
		class="btn btn-primary" value="" >
	  <i class="bi bi-save"></i>
	  {% translate 'Save annotation' %}
	</button>
      </form>
      <form method="post" action="{% url 'annotation:mark-valid' %}">
	{% csrf_token %}
	<input type="hidden" name="contents" value="">
	<button type="submit" id="btn-mark-valid"
		class="btn btn-success">
	  <i class="bi bi-check2"></i>
	  {% translate "Mark valid" %}
	</button>
      </form>
    </div>
  </div>
</div>
</main>
{% endblock %}

{% block page_scripts %}
<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<script src="{% static 'annotation/js/validation-flow.js' %}">
</script>
<script>
  let validationFlow = new ValidationFlow('image', 'editor',
					  'btn-save-annotation', 'btn-mark-valid',
					  ['contents']);
  validationFlow.initialize({{page_id}});
</script>
{% endblock %}